### ISSUE TITLE
Proposal: passing a function to @derive macro opts

### ISSUE THREAD

**Issue by GPrimola** [michalmuskala/jason#117] opened 2020-09-29 13:48 UTC
I'd like to propose the following option to `__deriving__` macro, so we could do something like that:

```elixir
@derive {Jason.Encoder, filter: &without_associations_not_loaded/1}

def without_associations_not_loaded(struct) do
  struct
    |> Map.from_struct()
    |> Enum.filter(fn
       {field, value} when is_map(value) ->
         value = Map.from_struct(value)

          not match?(%Ecto.Association.NotLoaded{}, value)
        _ -> true
      end)
end
```

WDYT?

**Comment by michalmuskala** [comment] 2020-09-29 13:51
I believe this is not a limitation of Jason, but of attributes in Elixir in general. I don't think there's anything we can do on our side.

In particular the issue is that the attribute is set before functions are compiled, so by the time you're setting it the function is not yet available.

**Comment by GPrimola** [comment] 2020-09-29 14:08
@michalmuskala got it! Do you think that anonymous function could do the trick?

**Comment by michalmuskala** [comment] 2020-09-29 16:54
I gave it a bit more thought, and TBH I'm not sure I see an advantage of that over writing the full implementation for the protocol manually. Leveraging `Jason.Encode.keyword/2` function, this could look like:

```elixir
defimpl Jason.Encoder, for: MyStruct do
  def encode(value, opts) do
    value
    |> Map.from_struct()
    |> Enum.reject(&match({_, %Ecto.Association.NotLoaded{}}, &1))
    |> Jason.Encode.keyword(opts)
  end
end
```

**Comment by GPrimola** [comment] 2020-09-29 17:57
@michalmuskala thank you very much! That's a much better solution, of course, since Jason.Encoder is a protocol! 

thanks again! :)

**Comment by michalmuskala** [comment] 2020-09-29 23:16
I'm going to close this now. Let me know if there's anything else 🙂

**Closed by michalmuskala** 2020-09-29 23:16 UTC
