### ISSUE TITLE
Strict option when decoding a JSON string with duplicate keys

### ISSUE THREAD

**Issue by tanguilp** [michalmuskala/jason#86] opened 2019-07-26 19:05 UTC
Mirror of https://github.com/michalmuskala/jason/issues/33

When decoding a JSON string which is an object with duplicate keys, Jason always returns the first value:

```elixir
iex> Jason.decode!(~s({"a": 1, "a": 2}))
%{"a" => 1}
iex> Jason.decode!(~s({"a": 2, "a": 1}))
%{"a" => 2}
```

It would be nice if there was an `:strict` option for the decode functions like for the encode ones.

I came to this implementing JWK Set Format (https://tools.ietf.org/html/rfc7517#section-15.12) which states:

>    The member names within a JWK Set MUST be unique; JWK Set parsers
>    MUST either reject JWK Sets with duplicate member names or use a JSON
>    parser that returns only the lexically last duplicate member name, as
>    specified in Section 15.12 ("The JSON Object") of ECMAScript 5.1
>    [ECMAScript].

which refers to page 204 (PDF page: 216) at http://www.ecma-international.org/ecma-262/5.1/ECMA-262.pdf (see the footnote).

I agree that it seems that most JSON decoders keep the last value (just try different JSON decoders online) and I guess that's why this has became the de-facto standard, even though the ECMA standard does apply only to browsers as far as I know.

**Comment by michalmuskala** [comment] 2020-03-17 21:44
Closing as duplicate of https://github.com/michalmuskala/jason/issues/33

**Closed by michalmuskala** 2020-03-17 21:44 UTC
